{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: forms-flow-custom-services
  {{- if or .Values.annotations .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.merge" (dict "values" (list .Values.annotations .Values.commonAnnotations) "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  SECRET_KEY: "{{ .Values.secretKey }}"
  JWT_SECRET_KEY: "{{ .Values.jwtSecretKey }}"
  JWT_EXPIRY_MINUTES: "{{ .Values.jwtExpiryMinutes }}"
{{- end }}