{{- if and .Values.immudb.enabled (not .Values.immudb.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "forms-flow-immudb.immudb.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "forms-flow-immudb.immudb.labels" . | nindent 4 }}
  {{- if or .Values.immudb.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.immudb.secretAnnotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  admin-password: {{ .Values.immudb.auth.adminPassword | default "immudb" | quote }}
{{- end }}
