{{- if and .Values.worker.enabled .Values.worker.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "forms-flow-immudb.worker.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "forms-flow-immudb.worker.labels" . | nindent 4 }}
  {{- if or .Values.worker.pdb.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.worker.pdb.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.worker.pdb.minAvailable }}
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.worker.pdb.maxUnavailable (not .Values.worker.pdb.minAvailable) }}
  maxUnavailable: {{ .Values.worker.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels: {{- include "forms-flow-immudb.worker.selectorLabels" . | nindent 6 }}
{{- end }}
