{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehr-connector.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "ehr-connector.labels" . | nindent 4 }}
  {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.secretAnnotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  epic-client-id: {{ .Values.epic.clientId | quote }}
  epic-kid: {{ .Values.epic.kid | quote }}
  epic-private-key: {{ .Values.epic.privateKey | quote }}
{{- end }}
